name: enently
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

# =========================
# DEPENDENCIES
# =========================
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: any
  provider: ^6.1.5+1
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_hooks: ^0.21.3+1

  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.3.0
  google_sign_in: ^6.2.1
  fluttertoast: ^9.0.0
  shared_preferences: ^2.5.5


# =========================
# DEV DEPENDENCIES
# =========================
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.0


# =========================
# FLUTTER NATIVE SPLASH
# =========================
flutter_native_splash:
  color: "#F4F7FF"
  image: assets/images/splsh_screen.png

  color_dark: "#000F30"
  image_dark: assets/images/splsh_screen.png

  android: true
  ios: true
  fullscreen: true
  
  branding: assets/images/branding.png
  branding_bottom_padding: 24

  android_12:
    color: "#F4F7FF"
    image: assets/images/splash12.png

    

    color_dark: "#000F30"
    image_dark: assets/images/splash12.png
    icon_background_color_dark: "#000F30"
   

# =========================
# LAUNCHER ICONS
# =========================
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon.png"

  remove_alpha_ios: true


# =========================
# FLUTTER CONFIG
# =========================
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/ligth_images/
    - assets/images/
    - assets/images/dark_images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600